### ISSUE TITLE
Out of date build

### ISSUE THREAD

**Issue by kurobeats** [maaaaz/CrackMapExecWin#1]
Looks like this build is one version behind.

**Comment by maaaaz** [comment]
This version is way behind but it is a reliable version with no UTF-8 error.
I should check the newest version to see there's major bug.

**Comment by MrJohnMalkovic** [comment]
Hey @maaaaz 

How did you overcame this error:
37562 INFO: Loading module hook "hook-gevent.py"...
38203 INFO: Determining a mapping of distributions to packages...
77157 WARNING: Unable to find package for requirement greenlet from package gevent.
77157 INFO: Packages required by gevent:
['cffi']

my steps were: 
-install python 2.7.17
-install pyinstaller
pyinstaller --onefile crackmapexec.py

I am trying to build a new version of CME. Any help would be appreciated. Thanks a lot in advance..

**Comment by MrJohnMalkovic** [comment]
I have cffi installed btw.

**Comment by maaaaz** [comment]
https://github.com/maaaaz/CrackMapExecWin/issues/6
