### ISSUE TITLE
Outdated Invoke-mimiktaz

### ISSUE THREAD

**Issue by berstrong** [maaaaz/CrackMapExecWin#2]
Tried to retreive logon passwords from a Windows 10 x64 based and got the following error:
ERROR kuhl_m_sekurlsa_acquireLSA ; Logon list

After dumping the lsass and extracting credentials offline using the latest mimikatz binaries, I could extract things

**Comment by maaaaz** [comment]
https://github.com/maaaaz/CrackMapExecWin/issues/6
