### ISSUE TITLE
Updating CME

### ISSUE THREAD

**Issue by CG-root** [maaaaz/CrackMapExecWin#6]
Hi :)
Any chance to update the tool?

**Comment by maaaaz** [comment]
Hello @CG-root,

I was considering recently, but someone else is more likely to do it before : https://twitter.com/mpgn_x64/status/1259465826157109252

**Comment by 3isenHeiM** [comment]
So this project is abandoned ?

**Comment by maaaaz** [comment]
No.
But if you want to compile it for yourself, there's already an [pyinstaller spec file in the official repo](https://github.com/byt3bl33d3r/CrackMapExec/blob/master/crackmapexec.spec).

**Comment by maaaaz** [comment]
https://twitter.com/mpgn_x64/status/1304553783398105103
